//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKSistemDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profesionalac : Igrac
    {
        public int Rang { get; set; }
        public int KlubIdKl { get; set; }
    
        public virtual Klub Klub { get; set; }
    }
}
