//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKSistemDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trener
    {
        public int IdTr { get; set; }
        public Nullable<int> KlubIdKl { get; set; }
        public string ImeTr { get; set; }
        public string PrzTr { get; set; }
    
        public virtual Klub Klub { get; set; }
    }
}
