//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKSistemDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zica
    {
        public int SifZic { get; set; }
        public string BojaZic { get; set; }
        public string MatZic { get; set; }
        public Nullable<int> ReketSifRek { get; set; }
        public Nullable<int> IgracIdIgr { get; set; }
    
        public virtual Reket Reket { get; set; }
        public virtual Igrac Igrac { get; set; }
    }
}
